{{- if .Values.applications.externalSecrets.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.applications.externalSecrets.name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.applications.externalSecrets.repo }}
    chart: {{ .Values.applications.externalSecrets.chart }}
    targetRevision: {{ .Values.applications.externalSecrets.targetRevision }}
    helm:
      values: |
        installCRDs: true
        serviceAccount:
          create: true
          name: external-secrets
          annotations:
            iam.gke.io/gcp-service-account: external-secrets@{{ .Values.global.projectId }}.iam.gserviceaccount.com
        nodeSelector:
          cloud.google.com/gke-nodepool: {{ .Values.global.nodePools.tools }}
        tolerations:
          - key: node-pool
            operator: Equal
            value: tools
            effect: NoSchedule
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.applications.externalSecrets.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
