{{- if .Values.applications.postgresExporterDb.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-exporter-db-secret
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.applications.postgresExporterDb.repo }}
    path: argocd/production/resources/postgres-exporter-db
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.applications.prometheus.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
