# ExternalSecret for Postgres Exporter (production). Syncs DB credentials from Secret Manager into monitoring namespace.
# Create secrets prod-db-user and prod-db-password in GCP Secret Manager (production project) if they do not exist.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-exporter-db
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: postgres-exporter-db
    creationPolicy: Owner
  data:
    - secretKey: user
      remoteRef:
        key: prod-db-user
    - secretKey: password
      remoteRef:
        key: prod-db-password
